version: '3'

services:
  server:
    image: node:18-alpine
    command: sh -c "cd server && npm install && npm run dev"
    ports:
      - 3000:3000
    working_dir: /server/
    volumes:
      - ./:/server
    environment:
      MONGO_INITDB_ROOT_USERNAME: mern
      MONGO_INITDB_ROOT_PASSWORD: secret
  mongo:
    image: arm64v8/mongo:7.0.0-rc3-jammy
    volumes:
      - mern-mongo-data:/data/db
    restart: always
    ports:
      - 27017:27017

volumes:
  mern-mongo-data:
    driver: local
