services:
  app:
    image: node:18-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MONGO_INITDB_ROOT_USERNAME: mern
      MONGO_INITDB_ROOT_PASSWORD: secret
  mongo:
    image: arm64v8/mongo:7.0.0-rc3-jammy
    volumes:
      - mern-mongo-data:/var/lib/mongo
    restart: always
    ports:
      - 27017:27017

volumes:
  mern-mongo-data: